name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Use npm v7
        run: npm i -g npm@7 --registry=https://registry.npmjs.org
        if: ${{ matrix.node-version == '12.x' || matrix.node-version == '14.x' }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Check DTS
        run: npx check-dts

      - name: Test
        run: npm run test -- --ci --coverage

      - name: Codecov
        run: npx codecov
